[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
cursive = "0.21.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.132"
chrono = "0.4.41"
ctrlc = "3.4.7"
tokio = { version = "1", features = ["full"] }
notify-rust = "4.11.7"